# Generated by Django 5.1 on 2024-08-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_url', models.URLField(max_length=500, unique=True)),
                ('shortcode', models.CharField(max_length=50)),
                ('owner_user', models.CharField(max_length=50)),
            ],
        ),
    ]
