# Generated by Django 5.1 on 2024-08-26 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagrampost',
            name='owner_user',
        ),
        migrations.RemoveField(
            model_name='instagrampost',
            name='shortcode',
        ),
    ]
