# Generated by Django 5.1 on 2024-08-26 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_remove_instagrampost_owner_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstagramPost',
        ),
    ]
