# Generated by Django 5.1 on 2024-08-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('downloader', '0003_delete_instagrampost'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_username', models.CharField(max_length=50)),
                ('owner_full_name', models.CharField(max_length=100)),
                ('owner_profile_pic', models.ImageField(upload_to='owner_profile/')),
                ('caption', models.TextField(blank=True, null=True)),
                ('post_date', models.DateTimeField()),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('post_video', models.FileField(blank=True, null=True, upload_to='post_videos/')),
                ('likes', models.CharField(max_length=50)),
                ('comments', models.CharField(max_length=50)),
            ],
        ),
    ]
